name: aetheric
description: "This is a simple and easy to use messenger application."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image: ^4.1.7
  image_picker: ^1.0.7
  slide_to_act: ^2.0.2
  another_flushbar: ^1.12.30
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  flutter_local_notifications: ^16.3.2
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.6.4
  firebase_analytics: ^10.7.4
  firebase_messaging: ^14.7.9
  firebase_crashlytics: ^3.4.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/launcher_inverted.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/launcher_inverted.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/launcher_inverted.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/launcher_inverted.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/google.png
    - assets/images/firebase.png
    - assets/images/flutter.png

