name: aetheric
description: "This is a simple and easy to use messenger application."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.13.6
  firebase_crashlytics: ^3.4.8
  firebase_analytics: ^10.7.4
  firebase_messaging: ^14.7.9
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  another_flushbar: ^1.12.30
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
